apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
  - deployment.yml
  - service.yml
  - namespace.yml
secretGenerator:
  - name: env
    files:
      - ticket-app-admin.json
    envs:
      - env.env
generatorOptions:
  disableNameSuffixHash: true