apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yml
  - ingress.yml
  - service.yml
  - managedCertificate.yml
secretGenerator:
  - name: env
    files:
      - ticket-app-admin.json
      - ticket-app-dns.json
    envs:
      - env.env
generatorOptions:
  disableNameSuffixHash: true