apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yml
  - service.yml
  - namespace.yml
  - issuer.yml
  - certificate.yml
secretGenerator:
  - name: env
    files:
      - ticket-app-admin.json
      - ticket-app-dns.json
    envs:
      - env.env
generatorOptions:
  disableNameSuffixHash: true