on:
  push:
    branches:
      - develop
env:
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/gcloud/auth@master
    - name: npm install, build
      run: |
        npm install
        cd src/functions && npm install
        cd ${GITHUB_WORKSPACE} && npm run build
    - name: set env
      run: |
        npx firebase use dev
    - name: deploy
      uses: actions/gcloud/cli@master
      with:
        args: app deploy
      env:
        CLOUDSDK_CORE_PROJECT: ticket-app-dev-11346