on:
  push:
    branches:
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID_DEV }}
        service_account_email: ${{ secrets.GCP_SA_EMAIL_DEV }}
        service_account_key: ${{ secrets.GCP_SA_KEY_DEV }}
        export_default_credentials: true
    - name: npm install, build
      run: |
        npm install
        cd src/functions && npm install
        cd ${GITHUB_WORKSPACE} && npm run build
    - name: set up
      run: |
        echo secrets.ENV_DEV > secret.yml
        npx firebase use dev
    - name: gae deploy
      run:
        npm run deploy
    - name: firebase deploy
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only functions
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}