on:
  push:
    branches:
      - develop
env:
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: npm install, build
      run: |
        npm install
        cd src/functions && npm install
        cd ${GITHUB_WORKSPACE} && npm run build
    - name: set env
      run: |
        echo ${{ secrets.ACCOUNT_KEY_PROD }} > ${GITHUB_WORKSPACE}/account_key.json
        export GOOGLE_APPLICATION_CREDENTIALS="${GITHUB_WORKSPACE}/account_key.json"
        npx firebase use dev
    - name: deploy
      run:
        npm run deploy